server:
  port: 8083
spring:
   data:
     mongodb:
       database: Bank
       host: localhost
       port: 27017
   application:
     name: movement-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j.circuitbreaker:
  instances:
    customers-cb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 8
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    products-cb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 8
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10