server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: resilience
          uri: https://github.com/neysistemas100/BootCamp
          search-paths: config-data
  application:
    name: config-service

